04 auth
Kolokol2002/hw-nodejs-rest-api pull request #3
Opened 2023-09-06 21:37 UTC by Kolokol2002

Підскажіть як краще обробляти помилки? бо я щось запутався з цим моментом, у мене є і клас для обробки помилок, і мідл вари, і не розумію що з цього треба а що ні. Якщо б ви підсказали як краще, був би вдячний

2023-09-06 21:37 UTC, Kolokol2002 commented
І гляньте чи все ок з репо? Можливо не правильно забловував гілку мастер.

2023-09-07 05:59 UTC, KhYulian commented
> Підскажіть як краще обробляти помилки? бо я щось запутався з цим моментом, у мене є і клас для обробки помилок, і мідл вари, і не розумію що з цього треба а що ні. Якщо б ви підсказали як краще, був би вдячний

і те і те 
тільки middleware у вас незакінчена 
app.use((err, req, res, next) => {
  res.status(500).json({ message: err.message });
});
статус захардкоджений, а має витягуватися з помилки

2023-09-07 06:00 UTC, KhYulian commented on controllers/users.js
> +    .send({ user: { token, email: req.body.email, subscription } });
```suggestion
    .json({ user: { token, email: req.body.email, subscription } });
```
json для відправки об'єкту

2023-09-07 06:00 UTC, KhYulian commented on controllers/users.js
> +    .send({ user: { token, email: req.body.email, subscription } });
всюди виправіть

2023-09-07 06:00 UTC, KhYulian commented on middlewares/validation.js
> +const validateParams = (schema) => {
```suggestion
const validateBody = (schema) => {
```

2023-09-07 06:00 UTC, KhYulian commented on middlewares/verefyToken.js
> +  console.log(!isUser && !isTokenVerify);
```suggestion
```

2023-09-07 06:01 UTC, KhYulian requested changes
залишив коменти

2023-09-07 11:52 UTC, Kolokol2002 commented on middlewares/validation.js
> +const validateParams = (schema) => {
Тут не зрозуміло? У мене є валідація боді і валідація парамсів

2023-09-07 17:10 UTC, KhYulian commented on middlewares/validation.js
> +const validateParams = (schema) => {
а для чого парамси валідувати? цього зазвичай не роблять. до того ж судячи з логіки це більше схоже на validateBody

2023-09-07 17:10 UTC, KhYulian approved these changes
Чудова робота, коменти візьміть до уваги при роботі над наступною

2023-09-09 12:20 UTC, merged